FROM ubuntu:20.04

RUN apt-get update 
RUN apt-get upgrade -y 
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs 
RUN npm install -g json-server
RUN apt-get remove -y curl