FROM ubuntu:14.04

RUN sudo apt-get update \
&& apt-get install -y curl  \
&& curl -sL deb.nodesource.com/setup_10.x | bash - \
&& apt-get install -y nodejs \
&& mkdir app \
&& apt-get remove -y curl \
&& rm -rf /var/lib/apt/lists/*

RUN npm install -g json-server

COPY db.json /app

WORKDIR /app

ENTRYPOINT [ "json-server", "--host", "0.0.0.0", "--watch", "db.json" ]