version: '3.3'
services:
  angular:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm install
    working_dir: /proyecto 
    volumes:
      - .:/proyecto
           

  angularrun:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    working_dir: /proyecto 
    volumes:
      - .:/proyecto
    ports:
      - "4200:4200"
    links:   
      - "angular"
  
  jsonserver:
    build: 
      context: .
      dockerfile: Dockerfile.jsonserver
    command: json-server --host 0.0.0.0 --watch db.json
    working_dir: /proyecto
    volumes: 
      - .:/proyecto
    ports:
      - "3000:3000"
    links: 
      - "angularrun"
